### ISSUE TITLE
Wouldn't it be cool if we did not have to specify a datasource ?

### ISSUE THREAD

**Issue by thadguidry** [LinkedDataFragments/Browser.js#2]
When I use Google Search... Google does not ask me which datasource to pick from for my results.

Let's see if there is a way to intelligently query the Web of LinkedDataFragments.

1. There needs to be an interactive discovery mechanism, whereby a user can do a keyword search to get suggestions of datasources to pick from, perhaps allow them to choose many or even none at all ?

If you look at this query... there are a few constraints in a where clause...and with those constraints, you know you must find an "author" named "Anne De Paepe", but that's about all you need to know, other than returning the title's of those publications.  This is not limited to just 1 datasource, that author might be in hundreds of datasources, so make discovery and query of those almost fool-proof.

```
SELECT ?title ?classification WHERE {
  ?author foaf:name "Anne De Paepe".
  ?publication dc:creator ?author;
               dc:title ?title;
               <http://lib.ugent.be/classification/classification> ?classification.
}
```

**Comment by RubenVerborgh** [comment]
Hi @thadguidry, it's definitely possible for some queries, but not for all.
@mielvds is currently researching a discovery mechanism, but there are still many hurdles to take, including the availability of interfaces. Another major problem is completeness, which you can never guarantee on an open Web. And then of course, Google has an index… centralization might not be the best way forward for the Semantic Web (remembering Sindice).

That said, if you combine [this approach](http://ruben.verborgh.org/blog/2015/01/30/600000-queryable-datasets-and-counting/) with metadata and discovery, many useful things can be done. Yet right now, finding linked datasources with "Anne De Paepe" in them is quite hard.

The general problem is not something we can solve in a few commits; this is a bigger architectural challenge for the entire Web of Data. While we'd be glad to take your suggestion into consideration, it will be a work of years. Would you therefore mind if we close the issue for now and mark it as "future"? :wink:

**Comment by thadguidry** [comment]
Uh, no.  Mark it "never - we'll be too tired, old and gray".

:) Thanks for the tips.

**Comment by RubenVerborgh** [comment]
We should get a roadmap out at some point! There's just so many roads now in front of us :smile:
