### ISSUE TITLE
Ask queries

### ISSUE THREAD

**Issue by rom1504** [LinkedDataFragments/Browser.js#3]
Does Browser.js handle ASK queries ?
for example : 
```sparql
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX res: <http://dbpedia.org/resource/>
ask where
{
	 res:Bill_Clinton dbo:child ?1.
}
```

It's easy to solve with a simple select query, for example : 
```sparql
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX res: <http://dbpedia.org/resource/>
select ?1 where
{
	 res:Bill_Clinton dbo:child ?1.
}
```

The select query works on http://client.linkeddatafragments.org/ but the ask query doesn't (it seems to be executing forever)

**Comment by RubenVerborgh** [comment]
HI @rom1504, thanks for reporting. It should indeed work… let me find out what the problem is.

**Comment by mielvds** [comment]
Although better error handling should be handled, I believe the ASK syntax is without WHERE:
From [SPARQL 1.1 Spec](http://www.w3.org/TR/sparql11-query/#ask):

    PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
    ASK  { ?x foaf:name  "Alice" ;
          foaf:mbox  <mailto:alice@work.example> }

**Comment by RubenVerborgh** [comment]
`WHERE` is indeed optional, but the query is valid.

I just remembered where the problem is though: we just don't have an outputter yet for `ASK` in the browser version :smile: I just need to create something so true or false is written.

**Comment by RubenVerborgh** [comment]
ASK and DESCRIBE queries are now supported in the jQuery version through 13a3f88265a8f678d95fc72e999415975648e701.
[Example query.](http://client.linkeddatafragments.org/#startFragment=http%3A%2F%2Fdata.linkeddatafragments.org%2Fdbpedia2014&query=PREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%0APREFIX%20res%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%0Aask%20where%0A%7B%0A%20%20%20%20%20res%3ABill_Clinton%20dbo%3Achild%20%3F1.%0A%7D)

Thanks again for reporting!

**Comment by rom1504** [comment]
Nice ! :)
